TasksMenager/Models/ViewModels/CompanyListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TasksMenager.Models.ViewModels
{
    public class CompanyListViewModel
    {
        public List<CompanyViewModel> Comapnies { get; set; }
        public bool NextPage { get; set; }
        public bool PreviousPage { get; set; }
        public int Page { get; set; }
    }
}

TasksMenager/Controllers/CompanyListController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using TasksMenager.Models.DatabaseModels;
using System.Linq;
using TasksMenager.Models.ViewModels;

namespace TasksMenager.Controllers
{
    public class CompanyListController : Controller
    {
        // GET: CompanyList
        [HttpGet]
        public ActionResult Index(int page)
        {
            ApplicationDbContext db = new ApplicationDbContext();

            var list = (from n in db.Companies select n).OrderBy(n=>n.CompanyId).Skip(page*10).Take(10).ToList();
            int count = (from n in db.Companies select n).Count();

            CompanyListViewModel companyListViewModel = new CompanyListViewModel
            {
                Comapnies = AutoMapper.Mapper.Map<List<Company>, List<CompanyViewModel>>(list),
                NextPage = (count > ((page + 1) * 10)),
                Page = page,
                PreviousPage = (page > 0)
            };

            return View(companyListViewModel);
        }
    }
}

TasksMenager/Views/CompanyList/Index.cshtml
@model TasksMenager.Models.ViewModels.CompanyListViewModel

@section title{
        <div class="align-self-start">
            Lista kontaktów
        </div>

        <div class="float-right">
            @Html.Name("Strona " + (Model.Page+1))
        </div>
}
<div class="row">
    <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Lp.</th>
                    <th scope="col">Nazwa</th>
                    <th scope="col">Miasto</th>
                    <th scope="col">Adres</th>
                </tr>
            </thead>
            <tbody>
                @{ int n = (Model.Page * 10) + 1;}
                @foreach (var m in Model.Comapnies)
                {
                    <tr>
                        <td>@Html.Name(n.ToString())</td>
                        @Html.Partial("_TablePartialView", m)
                    </tr>
                    n++;
                }
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col d-flex flex-column">
        <div class="align-self-end d-inline mb-2 mr-2" style="margin-top: auto;">
            @if (Model.NextPage)
            {
                <button type="button" class="btn btn-sm btn-primary" onclick="location.href='@Url.Action("Index", "CompanyList", new {page = Model.Page+1})'">Następna strona</button>
            }
            @if (Model.PreviousPage)
            {
                <button type="button" class="btn btn-sm btn-primary" onclick="location.href='@Url.Action("Index", "CompanyList", new {page = Model.Page-1})'">Poprzednia strona</button>
            }
        </div>
    </div>
</div>

TasksMenager/Views/CompanyList/_TablePartialView.cshtml
@model TasksMenager.Models.ViewModels.CompanyViewModel


    <td>@Html.Name(Model.Name)</td>
    <td>@Html.Name(Model.City)</td>
    <td>@Html.Name(Model.GetAddress())</td>